# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

#
# Site settings
#
#   ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
title                : "GJP's Blog (nl)"
email                :
description          : >- # this means to ignore newlines until the next variable
  Knowledge is power.
twitter_username     : gert.jan.paulissen@gmail.com
github_username      : gpaulissen
minimal_mistakes_skin: default
search               : true
url                  : 'https://gpaulissen.github.io'
repository           : gpaulissen/blog-nl
baseurl              : '/blog-nl'
highlighter          : rouge
encoding             : utf-8
destination          : _site
lang                 : 'nl'             # The language setting is used in /includes/header.html for html-settings
locale               : 'nl'

# Build settings
markdown             : kramdown
remote_theme         : mmistakes/minimal-mistakes
#theme                : minimal-mistakes-jekyll
# Outputting
permalink            : /:categories/:title/
paginate             : 5 # amount of posts to show
paginate_path        : /page:num/
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone             : CET

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#      ______                           ______          __          __
#     / ____/__  ____ ___       __     / ____/  _______/ /_  ______/ /__  _____
#    / / __/ _ \/ __ `__ \   __/ /_   / __/ | |/_/ ___/ / / / / __  / _ \/ ___/
#   / /_/ /  __/ / / / / /  /_  __/  / /____>  </ /__/ / /_/ / /_/ /  __(__  )
#   \____/\___/_/ /_/ /_/    /_/    /_____/_/|_|\___/_/\__,_/\__,_/\___/____/
#
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - README.md
    - INSTALL.md
    - vendor
    - html-validate.sh

author:
  name   : "Gert-Jan Paulissen"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Leven in Frankrijk als een Nederlander getrouwd met een Française"
  links:
    - label: "Over"
      icon: "fas fa-fw fa-link"
      url: "/blog-nl/over"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/gertjan.paulissen"
  
footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/gertjan.paulissen"

#       ____       ____            ____
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_
#   /_____/\___/_/  \__,_/\__,_/_/\__/
#
# Default Settings

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      sitemap: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sitemap: false

comments:
  provider: "custom"
  
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Frontpage-Layout-Settings
excerpt_separator: <!--more-->   # Use <!--more--> in your posts to generate an excerpt and a teaser

theme: jekyll-theme-minimal
