remote_theme         : ''
baseurl              : '/blog-nl'
theme                : minimal-mistakes-jekyll

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
